// This file is autogenerated by the hyperdispatch compiler
/* eslint-disable camelcase */

const { c, b4a, assert, DispatchError, ERRORS } = require('hyperdispatch/runtime')
const { version, getEncoding, setVersion } = require('./messages.js')

const defaultVersion = version

class Router {
  constructor () {
    this._handler0 = null
    this._handler1 = null
    this._handler2 = null
    this._handler3 = null
    this._handler4 = null
    this._handler5 = null
    this._handler6 = null
    this._handler7 = null
    this._handler8 = null
    this._handler9 = null
    this._handler10 = null
    this._handler11 = null
    this._handler12 = null
    this._handler13 = null
    this._handler14 = null
    this._handler15 = null

    this._missing = 16
  }

  add (name, handler) {
    switch (name) {
      case '@p2pcord/set-info':
        this._handler0 = handler
        break
      case '@p2pcord/add-member':
        this._handler1 = handler
        break
      case '@p2pcord/remove-member':
        this._handler2 = handler
        break
      case '@p2pcord/set-role':
        this._handler3 = handler
        break
      case '@p2pcord/set-name':
        this._handler4 = handler
        break
      case '@p2pcord/add-channel':
        this._handler5 = handler
        break
      case '@p2pcord/remove-channel':
        this._handler6 = handler
        break
      case '@p2pcord/add-invite':
        this._handler7 = handler
        break
      case '@p2pcord/use-invite':
        this._handler8 = handler
        break
      case '@p2pcord/remove-invite':
        this._handler9 = handler
        break
      case '@p2pcord/add-message':
        this._handler10 = handler
        break
      case '@p2pcord/edit-message':
        this._handler11 = handler
        break
      case '@p2pcord/remove-message':
        this._handler12 = handler
        break
      case '@p2pcord/set-successor':
        this._handler13 = handler
        break
      case '@p2pcord/add-rekey':
        this._handler14 = handler
        break
      case '@p2pcord/add-migrant':
        this._handler15 = handler
        break
      default:
        throw DispatchError.NONEXISTENT_ROUTE(name)
    }
    this._missing--
  }

  _checkAll () {
    assert(this._handler0 !== null, 'Missing handler for "@p2pcord/set-info"')
    assert(this._handler1 !== null, 'Missing handler for "@p2pcord/add-member"')
    assert(this._handler2 !== null, 'Missing handler for "@p2pcord/remove-member"')
    assert(this._handler3 !== null, 'Missing handler for "@p2pcord/set-role"')
    assert(this._handler4 !== null, 'Missing handler for "@p2pcord/set-name"')
    assert(this._handler5 !== null, 'Missing handler for "@p2pcord/add-channel"')
    assert(this._handler6 !== null, 'Missing handler for "@p2pcord/remove-channel"')
    assert(this._handler7 !== null, 'Missing handler for "@p2pcord/add-invite"')
    assert(this._handler8 !== null, 'Missing handler for "@p2pcord/use-invite"')
    assert(this._handler9 !== null, 'Missing handler for "@p2pcord/remove-invite"')
    assert(this._handler10 !== null, 'Missing handler for "@p2pcord/add-message"')
    assert(this._handler11 !== null, 'Missing handler for "@p2pcord/edit-message"')
    assert(this._handler12 !== null, 'Missing handler for "@p2pcord/remove-message"')
    assert(this._handler13 !== null, 'Missing handler for "@p2pcord/set-successor"')
    assert(this._handler14 !== null, 'Missing handler for "@p2pcord/add-rekey"')
    assert(this._handler15 !== null, 'Missing handler for "@p2pcord/add-migrant"')
  }

  async dispatch (message, context) {
    if (this._missing > 0) {
      this._checkAll()
    }

    setVersion(defaultVersion)

    const op = b4a.isBuffer(message) ? decode(message) : message

    switch (op.id) {
      case 0:
        return this._handler0(op.value, context)
      case 1:
        return this._handler1(op.value, context)
      case 2:
        return this._handler2(op.value, context)
      case 3:
        return this._handler3(op.value, context)
      case 4:
        return this._handler4(op.value, context)
      case 5:
        return this._handler5(op.value, context)
      case 6:
        return this._handler6(op.value, context)
      case 7:
        return this._handler7(op.value, context)
      case 8:
        return this._handler8(op.value, context)
      case 9:
        return this._handler9(op.value, context)
      case 10:
        return this._handler10(op.value, context)
      case 11:
        return this._handler11(op.value, context)
      case 12:
        return this._handler12(op.value, context)
      case 13:
        return this._handler13(op.value, context)
      case 14:
        return this._handler14(op.value, context)
      case 15:
        return this._handler15(op.value, context)
      default:
        throw DispatchError.HANDLER_NOT_FOUND_BY_ID(op.id)
    }
  }
}

function encode (name, message, { version = defaultVersion } = {}) {
  const state = { buffer: null, start: 0, end: 0 }

  const route = getRouteByName(name)
  setVersion(version)

  c.uint.preencode(state, route.id)
  route.enc.preencode(state, message)

  state.buffer = b4a.allocUnsafe(state.end)
  c.uint.encode(state, route.id)
  route.enc.encode(state, message)

  return state.buffer
}

function decode (buffer, { version = defaultVersion } = {}) {
  const state = { buffer, start: 0, end: buffer.length }

  const id = c.uint.decode(state)
  const route = getRouteById(id)
  setVersion(version)

  const value = route.enc.decode(state)
  return { id, name: route.name, value }
}

const route0 = {
  name: '@p2pcord/set-info',
  id: 0,
  enc: getEncoding('@p2pcord/info')
}

const route1 = {
  name: '@p2pcord/add-member',
  id: 1,
  enc: getEncoding('@p2pcord/member')
}

const route2 = {
  name: '@p2pcord/remove-member',
  id: 2,
  enc: getEncoding('@p2pcord/member-ref')
}

const route3 = {
  name: '@p2pcord/set-role',
  id: 3,
  enc: getEncoding('@p2pcord/member-role')
}

const route4 = {
  name: '@p2pcord/set-name',
  id: 4,
  enc: getEncoding('@p2pcord/member-name')
}

const route5 = {
  name: '@p2pcord/add-channel',
  id: 5,
  enc: getEncoding('@p2pcord/channel')
}

const route6 = {
  name: '@p2pcord/remove-channel',
  id: 6,
  enc: getEncoding('@p2pcord/channel-ref')
}

const route7 = {
  name: '@p2pcord/add-invite',
  id: 7,
  enc: getEncoding('@p2pcord/invite')
}

const route8 = {
  name: '@p2pcord/use-invite',
  id: 8,
  enc: getEncoding('@p2pcord/invite-ref')
}

const route9 = {
  name: '@p2pcord/remove-invite',
  id: 9,
  enc: getEncoding('@p2pcord/invite-ref')
}

const route10 = {
  name: '@p2pcord/add-message',
  id: 10,
  enc: getEncoding('@p2pcord/message')
}

const route11 = {
  name: '@p2pcord/edit-message',
  id: 11,
  enc: getEncoding('@p2pcord/message-edit')
}

const route12 = {
  name: '@p2pcord/remove-message',
  id: 12,
  enc: getEncoding('@p2pcord/message-ref')
}

const route13 = {
  name: '@p2pcord/set-successor',
  id: 13,
  enc: getEncoding('@p2pcord/successor')
}

const route14 = {
  name: '@p2pcord/add-rekey',
  id: 14,
  enc: getEncoding('@p2pcord/rekey')
}

const route15 = {
  name: '@p2pcord/add-migrant',
  id: 15,
  enc: getEncoding('@p2pcord/migrant')
}

function getRouteByName (name) {
  switch (name) {
    case '@p2pcord/set-info':
      return route0
    case '@p2pcord/add-member':
      return route1
    case '@p2pcord/remove-member':
      return route2
    case '@p2pcord/set-role':
      return route3
    case '@p2pcord/set-name':
      return route4
    case '@p2pcord/add-channel':
      return route5
    case '@p2pcord/remove-channel':
      return route6
    case '@p2pcord/add-invite':
      return route7
    case '@p2pcord/use-invite':
      return route8
    case '@p2pcord/remove-invite':
      return route9
    case '@p2pcord/add-message':
      return route10
    case '@p2pcord/edit-message':
      return route11
    case '@p2pcord/remove-message':
      return route12
    case '@p2pcord/set-successor':
      return route13
    case '@p2pcord/add-rekey':
      return route14
    case '@p2pcord/add-migrant':
      return route15
    default:
      throw DispatchError.ROUTE_NOT_FOUND_BY_NAME(name)
  }
}

function getRouteById (id) {
  switch (id) {
    case 0:
      return route0
    case 1:
      return route1
    case 2:
      return route2
    case 3:
      return route3
    case 4:
      return route4
    case 5:
      return route5
    case 6:
      return route6
    case 7:
      return route7
    case 8:
      return route8
    case 9:
      return route9
    case 10:
      return route10
    case 11:
      return route11
    case 12:
      return route12
    case 13:
      return route13
    case 14:
      return route14
    case 15:
      return route15
    default:
      throw DispatchError.HANDLER_NOT_FOUND_BY_ID(id)
  }
}

module.exports = {
  version,
  encode,
  decode,
  Router,
  DispatchError,
  ERRORS
}
