// This file is autogenerated by the hyperschema compiler
// Schema Version: 2
/* eslint-disable camelcase */
/* eslint-disable quotes */
/* eslint-disable space-before-function-paren */

const { c } = require('hyperschema/runtime')

const VERSION = 2

// eslint-disable-next-line no-unused-vars
let version = VERSION

// @p2pcord/info
const encoding0 = {
  preencode(state, m) {
    c.string.preencode(state, m.id)
    c.string.preencode(state, m.name)
    c.uint.preencode(state, m.kind)
    c.uint.preencode(state, m.created)
    state.end++ // max flag is 1 so always one byte

    if (version >= 2 && m.root) c.buffer.preencode(state, m.root)
  },
  encode(state, m) {
    const flags = (version >= 2 && m.root) ? 1 : 0

    c.string.encode(state, m.id)
    c.string.encode(state, m.name)
    c.uint.encode(state, m.kind)
    c.uint.encode(state, m.created)
    c.uint.encode(state, flags)

    if (version >= 2 && m.root) c.buffer.encode(state, m.root)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.string.decode(state)
    const r2 = c.uint.decode(state)
    const r3 = c.uint.decode(state)
    const flags = state.start < state.end ? c.uint.decode(state) : 0

    return {
      id: r0,
      name: r1,
      kind: r2,
      created: r3,
      root: (version >= 2 && (flags & 1) !== 0) ? c.buffer.decode(state) : null
    }
  }
}

// @p2pcord/member
const encoding1 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.writer)
    c.buffer.preencode(state, m.identity)
    c.buffer.preencode(state, m.signature)
    c.string.preencode(state, m.name)
    c.uint.preencode(state, m.role)
    c.uint.preencode(state, m.joined)
  },
  encode(state, m) {
    c.buffer.encode(state, m.writer)
    c.buffer.encode(state, m.identity)
    c.buffer.encode(state, m.signature)
    c.string.encode(state, m.name)
    c.uint.encode(state, m.role)
    c.uint.encode(state, m.joined)
  },
  decode(state) {
    const r0 = c.buffer.decode(state)
    const r1 = c.buffer.decode(state)
    const r2 = c.buffer.decode(state)
    const r3 = c.string.decode(state)
    const r4 = c.uint.decode(state)
    const r5 = c.uint.decode(state)

    return {
      writer: r0,
      identity: r1,
      signature: r2,
      name: r3,
      role: r4,
      joined: r5
    }
  }
}

// @p2pcord/member-ref
const encoding2 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.writer)
  },
  encode(state, m) {
    c.buffer.encode(state, m.writer)
  },
  decode(state) {
    const r0 = c.buffer.decode(state)

    return {
      writer: r0
    }
  }
}

// @p2pcord/member-role
const encoding3 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.writer)
    c.uint.preencode(state, m.role)
  },
  encode(state, m) {
    c.buffer.encode(state, m.writer)
    c.uint.encode(state, m.role)
  },
  decode(state) {
    const r0 = c.buffer.decode(state)
    const r1 = c.uint.decode(state)

    return {
      writer: r0,
      role: r1
    }
  }
}

// @p2pcord/member-name
const encoding4 = {
  preencode(state, m) {
    c.string.preencode(state, m.name)
  },
  encode(state, m) {
    c.string.encode(state, m.name)
  },
  decode(state) {
    const r0 = c.string.decode(state)

    return {
      name: r0
    }
  }
}

// @p2pcord/channel
const encoding5 = {
  preencode(state, m) {
    c.string.preencode(state, m.id)
    c.string.preencode(state, m.name)
    c.uint.preencode(state, m.kind)
    c.uint.preencode(state, m.position)
  },
  encode(state, m) {
    c.string.encode(state, m.id)
    c.string.encode(state, m.name)
    c.uint.encode(state, m.kind)
    c.uint.encode(state, m.position)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.string.decode(state)
    const r2 = c.uint.decode(state)
    const r3 = c.uint.decode(state)

    return {
      id: r0,
      name: r1,
      kind: r2,
      position: r3
    }
  }
}

// @p2pcord/channel-ref
const encoding6 = {
  preencode(state, m) {
    c.string.preencode(state, m.id)
  },
  encode(state, m) {
    c.string.encode(state, m.id)
  },
  decode(state) {
    const r0 = c.string.decode(state)

    return {
      id: r0
    }
  }
}

// @p2pcord/invite
const encoding7 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.id)
    c.buffer.preencode(state, m.invite)
    c.buffer.preencode(state, m.publicKey)
    c.uint.preencode(state, m.expires)
    c.uint.preencode(state, m.maxUses)
    c.uint.preencode(state, m.uses)
    c.buffer.preencode(state, m.createdBy)
    state.end++ // max flag is 1 so always one byte
  },
  encode(state, m) {
    const flags = (version >= 2 && m.restricted) ? 1 : 0

    c.buffer.encode(state, m.id)
    c.buffer.encode(state, m.invite)
    c.buffer.encode(state, m.publicKey)
    c.uint.encode(state, m.expires)
    c.uint.encode(state, m.maxUses)
    c.uint.encode(state, m.uses)
    c.buffer.encode(state, m.createdBy)
    c.uint.encode(state, flags)
  },
  decode(state) {
    const r0 = c.buffer.decode(state)
    const r1 = c.buffer.decode(state)
    const r2 = c.buffer.decode(state)
    const r3 = c.uint.decode(state)
    const r4 = c.uint.decode(state)
    const r5 = c.uint.decode(state)
    const r6 = c.buffer.decode(state)
    const flags = state.start < state.end ? c.uint.decode(state) : 0

    return {
      id: r0,
      invite: r1,
      publicKey: r2,
      expires: r3,
      maxUses: r4,
      uses: r5,
      createdBy: r6,
      restricted: (version >= 2 && (flags & 1) !== 0)
    }
  }
}

// @p2pcord/invite-ref
const encoding8 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.id)
  },
  encode(state, m) {
    c.buffer.encode(state, m.id)
  },
  decode(state) {
    const r0 = c.buffer.decode(state)

    return {
      id: r0
    }
  }
}

// @p2pcord/file
const encoding9 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.core)
    c.uint.preencode(state, m.blockOffset)
    c.uint.preencode(state, m.blockLength)
    c.uint.preencode(state, m.byteOffset)
    c.uint.preencode(state, m.byteLength)
    c.string.preencode(state, m.name)
    c.string.preencode(state, m.mime)
  },
  encode(state, m) {
    c.buffer.encode(state, m.core)
    c.uint.encode(state, m.blockOffset)
    c.uint.encode(state, m.blockLength)
    c.uint.encode(state, m.byteOffset)
    c.uint.encode(state, m.byteLength)
    c.string.encode(state, m.name)
    c.string.encode(state, m.mime)
  },
  decode(state) {
    const r0 = c.buffer.decode(state)
    const r1 = c.uint.decode(state)
    const r2 = c.uint.decode(state)
    const r3 = c.uint.decode(state)
    const r4 = c.uint.decode(state)
    const r5 = c.string.decode(state)
    const r6 = c.string.decode(state)

    return {
      core: r0,
      blockOffset: r1,
      blockLength: r2,
      byteOffset: r3,
      byteLength: r4,
      name: r5,
      mime: r6
    }
  }
}

// @p2pcord/message.files
const encoding10_5 = c.array(c.frame(encoding9))

// @p2pcord/message
const encoding10 = {
  preencode(state, m) {
    c.string.preencode(state, m.channel)
    c.string.preencode(state, m.id)
    c.buffer.preencode(state, m.author)
    c.string.preencode(state, m.text)
    c.uint.preencode(state, m.ts)
    state.end++ // max flag is 4 so always one byte

    if (m.files) encoding10_5.preencode(state, m.files)
    if (m.replyTo) c.string.preencode(state, m.replyTo)
    if (m.edited) c.uint.preencode(state, m.edited)
  },
  encode(state, m) {
    const flags = (m.files ? 1 : 0) | (m.replyTo ? 2 : 0) | (m.edited ? 4 : 0)

    c.string.encode(state, m.channel)
    c.string.encode(state, m.id)
    c.buffer.encode(state, m.author)
    c.string.encode(state, m.text)
    c.uint.encode(state, m.ts)
    c.uint.encode(state, flags)

    if (m.files) encoding10_5.encode(state, m.files)
    if (m.replyTo) c.string.encode(state, m.replyTo)
    if (m.edited) c.uint.encode(state, m.edited)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.string.decode(state)
    const r2 = c.buffer.decode(state)
    const r3 = c.string.decode(state)
    const r4 = c.uint.decode(state)
    const flags = c.uint.decode(state)

    return {
      channel: r0,
      id: r1,
      author: r2,
      text: r3,
      ts: r4,
      files: (flags & 1) !== 0 ? encoding10_5.decode(state) : null,
      replyTo: (flags & 2) !== 0 ? c.string.decode(state) : null,
      edited: (flags & 4) !== 0 ? c.uint.decode(state) : 0
    }
  }
}

// @p2pcord/message-edit
const encoding11 = {
  preencode(state, m) {
    c.string.preencode(state, m.channel)
    c.string.preencode(state, m.id)
    c.string.preencode(state, m.text)
    c.uint.preencode(state, m.ts)
  },
  encode(state, m) {
    c.string.encode(state, m.channel)
    c.string.encode(state, m.id)
    c.string.encode(state, m.text)
    c.uint.encode(state, m.ts)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.string.decode(state)
    const r2 = c.string.decode(state)
    const r3 = c.uint.decode(state)

    return {
      channel: r0,
      id: r1,
      text: r2,
      ts: r3
    }
  }
}

// @p2pcord/message-ref
const encoding12 = {
  preencode(state, m) {
    c.string.preencode(state, m.channel)
    c.string.preencode(state, m.id)
  },
  encode(state, m) {
    c.string.encode(state, m.channel)
    c.string.encode(state, m.id)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.string.decode(state)

    return {
      channel: r0,
      id: r1
    }
  }
}

// @p2pcord/successor
const encoding13 = {
  preencode(state, m) {
    c.string.preencode(state, m.id)
    c.buffer.preencode(state, m.ref)
  },
  encode(state, m) {
    c.string.encode(state, m.id)
    c.buffer.encode(state, m.ref)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.buffer.decode(state)

    return {
      id: r0,
      ref: r1
    }
  }
}

// @p2pcord/rekey
const encoding14 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.to)
    c.buffer.preencode(state, m.ref)
    c.buffer.preencode(state, m.box)
  },
  encode(state, m) {
    c.buffer.encode(state, m.to)
    c.buffer.encode(state, m.ref)
    c.buffer.encode(state, m.box)
  },
  decode(state) {
    const r0 = c.buffer.decode(state)
    const r1 = c.buffer.decode(state)
    const r2 = c.buffer.decode(state)

    return {
      to: r0,
      ref: r1,
      box: r2
    }
  }
}

// @p2pcord/migrant
const encoding15 = {
  preencode(state, m) {
    c.buffer.preencode(state, m.identity)
    c.uint.preencode(state, m.role)
    c.string.preencode(state, m.name)
  },
  encode(state, m) {
    c.buffer.encode(state, m.identity)
    c.uint.encode(state, m.role)
    c.string.encode(state, m.name)
  },
  decode(state) {
    const r0 = c.buffer.decode(state)
    const r1 = c.uint.decode(state)
    const r2 = c.string.decode(state)

    return {
      identity: r0,
      role: r1,
      name: r2
    }
  }
}

function setVersion(v) {
  version = v
}

function encode(name, value, v = VERSION) {
  version = v
  return c.encode(getEncoding(name), value)
}

function decode(name, buffer, v = VERSION) {
  version = v
  return c.decode(getEncoding(name), buffer)
}

function getEnum(name) {
  switch (name) {
    default:
      throw new Error('Enum not found ' + name)
  }
}

function getEncoding(name) {
  switch (name) {
    case '@p2pcord/info':
      return encoding0
    case '@p2pcord/member':
      return encoding1
    case '@p2pcord/member-ref':
      return encoding2
    case '@p2pcord/member-role':
      return encoding3
    case '@p2pcord/member-name':
      return encoding4
    case '@p2pcord/channel':
      return encoding5
    case '@p2pcord/channel-ref':
      return encoding6
    case '@p2pcord/invite':
      return encoding7
    case '@p2pcord/invite-ref':
      return encoding8
    case '@p2pcord/file':
      return encoding9
    case '@p2pcord/message':
      return encoding10
    case '@p2pcord/message-edit':
      return encoding11
    case '@p2pcord/message-ref':
      return encoding12
    case '@p2pcord/successor':
      return encoding13
    case '@p2pcord/rekey':
      return encoding14
    case '@p2pcord/migrant':
      return encoding15
    default:
      throw new Error('Encoder not found ' + name)
  }
}

function getStruct(name, v = VERSION) {
  const enc = getEncoding(name)
  return {
    preencode(state, m) {
      version = v
      enc.preencode(state, m)
    },
    encode(state, m) {
      version = v
      enc.encode(state, m)
    },
    decode(state) {
      version = v
      return enc.decode(state)
    }
  }
}

const resolveStruct = getStruct // compat

module.exports = {
  resolveStruct,
  getStruct,
  getEnum,
  getEncoding,
  encode,
  decode,
  setVersion,
  version
}
