// Vite plugin for the web app build: web app manifest, home screen icons and
// a service worker, so the page can be added to the iPhone home screen and
// starts without network (it still needs a bridge to do anything useful).
import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

const icon = (size) => fileURLToPath(new URL(`../../build/icon/icon-${size}x${size}.png`, import.meta.url))

export function webApp ({ version }) {
  return {
    name: 'p2pcord-web-app',
    transformIndexHtml (html) {
      return html.replace(
        '</head>',
        [
          '    <link rel="manifest" href="./manifest.webmanifest" />',
          '    <link rel="apple-touch-icon" href="./icon-180.png" />',
          '    <link rel="icon" type="image/png" href="./icon-192.png" />',
          '    <meta name="theme-color" content="#1e1f22" />',
          '    <meta name="mobile-web-app-capable" content="yes" />',
          '    <meta name="apple-mobile-web-app-capable" content="yes" />',
          '    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />',
          '    <meta name="apple-mobile-web-app-title" content="P2Pcord" />',
          '    <script src="./register-sw.js" defer></script>',
          '  </head>'
        ].join('\n')
      ).replace('width=device-width, initial-scale=1', 'width=device-width, initial-scale=1, viewport-fit=cover')
    },
    generateBundle (options, bundle) {
      const png = (size, name) => this.emitFile({ type: 'asset', fileName: name, source: readFileSync(icon(size)) })
      png(256, 'icon-180.png') // iOS scales it down
      png(256, 'icon-192.png')
      png(512, 'icon-512.png')
      // No start_url on purpose: iOS then keeps the address the page was
      // added from, including a #bridge=... code
      this.emitFile({
        type: 'asset',
        fileName: 'manifest.webmanifest',
        source: JSON.stringify({
          name: 'P2Pcord',
          short_name: 'P2Pcord',
          description: 'P2Pcord im Browser – verbunden über die App eines Freundes',
          display: 'standalone',
          background_color: '#1e1f22',
          theme_color: '#1e1f22',
          icons: [
            { src: 'icon-192.png', sizes: '256x256', type: 'image/png' },
            { src: 'icon-512.png', sizes: '512x512', type: 'image/png', purpose: 'any maskable' }
          ]
        }, null, 2)
      })
      this.emitFile({
        type: 'asset',
        fileName: 'register-sw.js',
        source: "if ('serviceWorker' in navigator) navigator.serviceWorker.register('./sw.js').catch(() => {})\n"
      })
      // The app shell is cached up front; the large noise-suppression model on first use
      const shell = ['./', './index.html', ...Object.keys(bundle).filter((f) => !f.startsWith('dfn3/')).map((f) => './' + f)]
      this.emitFile({ type: 'asset', fileName: 'sw.js', source: serviceWorker(version + '-' + Date.now().toString(36), shell) })
    }
  }
}

function serviceWorker (tag, shell) {
  return `// Generated by renderer/web/plugin.mjs
const CACHE = 'p2pcord-${tag}'
const SHELL = ${JSON.stringify(shell)}

self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(SHELL)).then(() => self.skipWaiting()))
})

self.addEventListener('activate', (e) => {
  e.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k.startsWith('p2pcord-') && k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  )
})

// Pages: network first, so a new version shows up on the next start.
// Everything else (hashed assets, models): cache first.
self.addEventListener('fetch', (e) => {
  const req = e.request
  if (req.method !== 'GET' || new URL(req.url).origin !== location.origin) return
  if (req.mode === 'navigate') {
    e.respondWith(fetch(req).catch(() => caches.match('./index.html')))
    return
  }
  e.respondWith(
    caches.match(req).then((hit) => hit || fetch(req).then((res) => {
      if (res.ok && res.type === 'basic') {
        const copy = res.clone()
        caches.open(CACHE).then((c) => c.put(req, copy))
      }
      return res
    }))
  )
})
`
}
